Overhaul CI - to be split in multiple commits

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,8 @@ on:
   pull_request:
 
 env:
-  CONSUL_VERSION: 1.6.1
+  DOTNET_NOLOGO: true
+  DOTNET_MULTILEVEL_LOOKUP: false
 
 jobs:
 
@@ -35,28 +36,42 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-18.04, windows-2019, macos-10.15]
+        component: [Consul, Consul.AspNetCore]
+        consul: [1.6.10, 1.7.10, 1.8.6, 1.9.0]
+        exclude:
+          - component: Consul.AspNetCore
+            consul: 1.7.10
+          - component: Consul.AspNetCore
+            consul: 1.8.6
+          - component: Consul.AspNetCore
+            consul: 1.9.0
       fail-fast: false
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Setup .NET Core SDK
-        if: runner.os != 'Windows'
+      # TODO remove this if we don't test it anymore
+      - name: Setup .NET Core SDK 2.1
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 2.1.811
+      - name: Setup .NET Core SDK 3.1
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 3.1.404
       - name: Download Consul
+        if: matrix.component == 'Consul'
         shell: bash
         run: |
           cd Consul.Test
           SYSTEM=$(uname | sed 's/MINGW.*/windows/' | tr A-Z a-z)
-          curl -sSL https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_${SYSTEM}_amd64.zip -o consul.zip
+          curl -sSL https://releases.hashicorp.com/consul/${{ matrix.consul }}/consul_${{ matrix.consul }}_${SYSTEM}_amd64.zip -o consul.zip
           unzip consul.zip
           rm consul.zip
       - name: Build
-        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true
+        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true ${{ matrix.component }}.Test
       - name: Repack
-        if: runner.os == 'Windows'
+        if: runner.os == 'Windows' && matrix.component == 'Consul'
         run: |
           cd Consul/bin/Release
           mv net461 net461unmerged
@@ -68,23 +83,27 @@ jobs:
       - name: Run tests
         shell: bash
         run: |
-          cd Consul.Test
-          ./consul agent -dev -config-file test_config.json -log-file consul.log >consul-stdout.log 2>consul-stderr.log &
-          dotnet test --configuration=Release --no-build -v=Normal
+          cd ${{ matrix.component }}.Test
+          if [ "${{ matrix.component }}" == "Consul" ]
+          then
+            ./consul agent -dev -config-file test_config.json -log-file consul.log >consul-stdout.log 2>consul-stderr.log &
+          fi
+          dotnet test --configuration=Release --no-build --logger "GitHubActions;report-warnings=false"
       - name: Upload Consul logs
-        if: failure()
+        if: failure() && matrix.component == 'Consul'
         uses: actions/upload-artifact@v2
         with:
-          name: consul-logs-${{ matrix.os }}
+          name: consul-logs-${{ matrix.os }}_consul-${{ matrix.consul }}
           path: Consul.Test/consul*.log
       - name: Create NuGet package
-        if: runner.os == 'Windows'
+        if: runner.os == 'Windows' && startsWith(matrix.consul, '1.6')
         run: |
-          if ("${{ github.ref }}" -like "refs/tags/v*") {
-            $tag = "${{ github.ref }}".SubString(11)
-            $version = (Select-Xml -path Consul/Consul.csproj -XPath "/Project/PropertyGroup/VersionPrefix/text()").node.Value
+          $prefix = "${{ matrix.component }}" -eq "Consul.AspNetCore" ? "Consul.AspNetCore_" : ""
+          if ("${{ github.ref }}" -match "^refs/tags/${prefix}v(\d+\.\d+.*)") {
+            $tag = $Matches[1]
+            $version = (Select-Xml -path ${{ matrix.component }}/${{ matrix.component }}.csproj -XPath "/Project/PropertyGroup/VersionPrefix/text()").node.Value
             if (-not ($tag -eq $version)) {
-              echo "There is a mismatch between the project version ($version) and the tag ($tag)"
+              echo "::error ::There is a mismatch between the project version ($version) and the tag ($tag)"
               exit 1
             }
           } else {
@@ -95,25 +114,46 @@ jobs:
             $suffix = 'g' + $(git rev-parse --short HEAD)
             $params = "--version-suffix", $suffix
           }
-          dotnet pack --configuration=Release --no-build @params Consul/Consul.csproj
+          dotnet pack --configuration=Release --no-build @params ${{ matrix.component }}
       - name: Upload NuGet package artifact
-        if: runner.os == 'Windows'
+        if: runner.os == 'Windows' && startsWith(matrix.consul, '1.6')
         uses: actions/upload-artifact@v2
         with:
-          name: nuget-package
-          path: dist/consul
+          name: nuget-package-${{ matrix.component }}
+          path: dist
 
   # Publish NuGet package when a tag is pushed.
-  # Tests need to succeed on all platforms first, including having a tag name that matches the version number.
+  # Tests need to succeed for all components and on all platforms first,
+  # including having a tag name that matches the version number.
   publish:
-    if: startsWith(github.ref, 'refs/tags/v')
+    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/Consul.AspNetCore_v')
     needs: build
     runs-on: ubuntu-18.04
     steps:
+      - name: Get component
+        id: get-component
+        run: |
+          case "${{ github.ref }}" in
+            refs/tags/v*)
+              component="Consul"
+              ;;
+            refs/tags/Consul.AspNetCore_v*)
+              component="Consul.AspNetCore"
+              ;;
+            *)
+              echo "::error ::This job should never run for something else than a version tag. Something must have gone very wrong!"
+              exit 1
+              ;;
+          esac
+          echo "::set-output name=component::$component"
       - name: Download NuGet package artifact
         uses: actions/download-artifact@v2
         with:
-          name: nuget-package
-          path: dist/consul
+          name: nuget-package-${{ steps.get-component.outputs.component }}
+          path: dist
+      - name: Setup .NET Core SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 3.1.404
       - name: Publish to NuGet
-        run: dotnet nuget push dist/consul/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+        run: dotnet nuget push dist/${{ steps.get-component.outputs.component }}*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
